### ISSUE TITLE
esb only works with RATE_2MBIT

### ISSUE THREAD

**Issue by zerog2k** [virtualabs/radiobit#2]
esb mode seems to only work when my PTX is using 2Mbps datarate. (Setting 1Mbps doesnt receive anything.)

```
radio.on()
radio.config(data_rate=radio.RATE_1MBIT, ...)
radio.esb()
...
```

is 2Mbps being hardcoded in esb?
https://github.com/virtualabs/radiobit/blob/master/micropython/source/microbit/modradio.cpp#L553-L555

**Comment by virtualabs** [comment]
When enabling the ESB mode, the data_rate is forced to 2Mbit by default, but there is a way to change it dynamically:

`
radio.on()
radio.config(...)
radio.esb()
radio.config(data_rate=radio.RATE_1MBIT)
`
It is a bit tricky but that should do the job ;)

**Comment by zerog2k** [comment]
thanks that works for me
